work_dir: "/work/05690/isaiahk/maverick/ncinet/checkpoints"

ingest_config:
  full_archive_name: "data_full.npz"
  archive_dir: "/work/05690/isaiahk/maverick/ncinet/saves"
  nci_dir: "/work/projects/SD2E-Community/prod/data/protein-design/data_v1_April_2018/nci_data"
  score_path: !!python/tuple
    - "/work/projects/SD2E-Community/prod/data/protein-design/data_v1_April_2018/aggregated_v1_data_Hamed_May_23_2018/consistent_training_data_v1.csv"
    - "/work/projects/SD2E-Community/prod/data/protein-design/data_v1_April_2018/aggregated_v1_data_Hamed_May_23_2018/consistent_testing_data_v1.csv"
  ingest_version: 'sd2_dataframes_v2'
  topo_index_name: 'topo_index.yml'
  archive_prefix: "data"
  tt_tags: !!python/tuple ["train", "eval"]
  xv_tags: !!python/tuple ["xvTrain", "xvVal"]

request_config: {}

training_config:
  batch_size: 64
  log_frequency: 25
  summary_steps: 100
  checkpoint_secs: 120
  input_noise: 0.05

eval_config:
  batch_size: 128
  eval_interval: 120
